language: r
r: bioc-devel
cache: packages
r_github_packages:
- jimhester/covr
notifications:
  slack:
    rooms:
      secure: FslsSEU2U/Erx3upc42cvyU5c9EFfmMGDIWrHR13IltjJr0EeBJ/wYN51CRszVtO0QHPwiyNizrtdobHGq8rc6F0Tdr0a967Kb1Yu+sJDMpZV5zQoaeO2Vb8yitEuG6Vrcn8EnQlKGsQLWaIkk/gOK1QMYpShACQzzUqBdiOjGpkcT0l2hVV4EuViiZAv1exH7wh84dKIEw45Msss60nZZGpwj3XL/V1RtD3vufMgtF0/VCCdCqIyC0D9WdioiF3A57UhFVp0lVE/HlIG4Ji0sQlqYVzZE+caaZ2VQxPZkGBJ8R23lMH0nL7LPb7v/rB0haEAFZQSUpNYQMQRucTN8ZFp/7045BFAVTBu0Qb5CcuD0tFXNJg3dXJ/mUfOrIbh46UIOHwZnq/WjAuo95JS/mY1k7b8FkIAC+uSMUbAjWgOl6GdyhSNbbBhh2vPGtFlT8WQ0d/A4zDzhXcgTHpjSYTigVo3gis7UNngRCyIUB3ojVDi2C/JcFvNJSMjYoFZqJiNTbkBAljT9OIutUY4nWnpuZxTsbfUdmXFOQKIHqRNJ6HRwPbS5Zhu9hfelj6hdy9f78cn8Np2kNtoTTG/EaHmjhBXVHfJ5Ga9sOxJufbljIZI85HxGKVZzsmPR7319STlUsH4An+CnrzOXlV/uCztjzmwVfBBwv1ZJKRc3M=
