---
title: "pharmacogx_ggplot"
author: "Niklas Rindtorff"
date: "11/21/2017"
output: html_document
---

These are excerpts I stored away. I don't think I need it anymore. 

```{r, warning=FALSE, eval = FALSE}
dodge <- position_dodge(width=0.15)
ctg_qnorm %>%
   ## separate annotation of screen name 
  separate(screen, c("date", "operator", "mithras", "full_barcode"), remove = FALSE) %>%
  separate(full_barcode, c("line", "plate", "library"), remove = FALSE, sep = c(7, 11)) %>%
  group_by(screen, drug) %>% arrange(rack.concentration) %>% 
  dplyr::rename(concentration_factor = rack.concentration) %>% 
  #filter(drug %in% c( "Methotrexate", "Birinapant",  "Ponatinib",  "Nutlin3a", 
  #                   "Panobinostat", "Erlotinib")) %>%
  filter(drug %in% c( "Gefitinib", "Erlotinib")) %>%
  ungroup() %>%
  mutate(line = as.factor(line),
         # drug = factor(drug)) %>%
         drug = factor(drug, levels = c(
                    "Gefitinib", "Erlotinib"))) %>%
  group_by(line, drug, concentration_factor) %>%
     dplyr::summarise(mean_photons = mean(pc_norm, na.rm = TRUE),
                     sd_photons = sd(pc_norm, na.rm = TRUE)) %>%
    full_join(., ras) %>%
    ggplot(aes(y = mean_photons, x = concentration_factor)) + 
    geom_smooth(aes(group = line, color = ras)) +
    geom_point(position = dodge,  stat = "identity",  size = 2, shape=1)  + 
    # geom_path(aes(group = line), , colour = "black", alpha = 0.6, position = dodge, size = 2) + 
    #geom_errorbar(aes(ymin=mean_photons-sd_photons, ymax=mean_photons+sd_photons, group = line), width=0, position = dodge, size = 1, alpha = 0.5) +
    #geom_ribbon( aes(x=concentration_factor, y=mean_photons, ymin=mean_photons-sd_photons, ymax=mean_photons+sd_photons), alpha=0.2) +
    #scale_x_log10(breaks = c(7,14)) + 
    #scale_shape_discrete(solid=FALSE) +
    ylab("Photon count normalized to control") + 
    facet_wrap(~drug) + 
    xlab("Concentration factor") + 
    theme_classic()
```

```{r, warning=F, eval = FALSE}
## predict viability from concentration data and curve parameters
.Hill<-function(x, pars) {
  return(pars[2] + (1 - pars[2]) / (1 + (10 ^ x / 10 ^ pars[3]) ^ pars[1]))
}
.GetSupportVec <- function(x, output_length = 1001) {
  return(seq(from = min(x), to = max(x), length.out = output_length))
}

tidy_loglogistic <- function(df){
  viability = df$pc_norm %>% as.character() 
  conc = df$rack.concentration

  log_logistic_params <- logLogisticRegression(conc = conc, viability = viability, viability_as_pct = FALSE)
  log10_x_vals <- .GetSupportVec(log10(conc %>% as.numeric()))
  out <- tibble(fit = .Hill(log10_x_vals, pars=c(log_logistic_params$HS, log_logistic_params$E_inf/100, log10(log_logistic_params$EC50))) * 100,
         concentration = 10 ^ log10_x_vals) %>%
    mutate(line = df$line %>% unique(),
           drug = df$drug %>% unique())
  return(out)}

ctg_qnorm_tidy <- ctg_qnorm %>%
   ## separate annotation of screen name 
  separate(screen, c("date", "operator", "mithras", "full_barcode"), remove = FALSE) %>%
  separate(full_barcode, c("line", "plate", "library"), remove = FALSE, sep = c(7, 11)) %>%
  group_by(line, drug) %>% arrange(rack.concentration) 

loglogistic <- ctg_qnorm_tidy %>%
  #filter(drug == "YM155" & line == "D007T01") %>%
  do(tidy_loglogistic(.)) 

save(loglogistic, file = "loglogistic.Rdata")
save(ctg_qnorm_tidy, file = "ctg_qnorm_tidy.Rdata")
```

The logLogisitc fit is still not optimal. More work is needed. 

```{r, warning=F}
load("loglogistic.Rdata")
#define variables
# coi <- c("Gefitinib", "Erlotinib", "Dasatinib")
# loi <- c("D007T01", "D027T01")
coi <- c("Gefitinib")
loi <- c("D027T01")


#plot curves of defined organoids
loglogistic %>% 
  full_join(., ras) %>%
  filter(drug %in% coi & line %in% loi) %>% 
  ggplot(aes(concentration, fit)) + 
  geom_line(aes(group = line, color = line)) + 
  geom_point(data = ctg_qnorm_tidy %>%
             filter(drug %in% coi & line %in% loi),
             aes(rack.concentration %>% as.numeric(), pc_norm*100, color = line),
             size = 3, shape=1) +
  ylab("Photon count normalized to control") + 
  xlab("Concentration factor") + 
  scale_x_log10() +
  theme_classic() + 
  facet_grid(~ drug)

#plot curvbes of all organoids
# loglogistic %>% 
#   full_join(., ras) %>%
#   filter(drug %in% coi) %>% 
#   ggplot(aes(concentration, fit)) + 
#   geom_line(aes(group = line, color = ras)) + 
#   geom_point(data = ctg_qnorm_tidy %>% full_join(., ras) %>%
#              filter(drug %in% coi),
#              aes(rack.concentration %>% as.numeric(), pc_norm*100, color = ras),
#              size = 3, shape=1) +
#   ylab("Photon count normalized to control") + 
#   xlab("Concentration factor") + 
#   scale_x_log10() +
#   theme_classic() + 
#   facet_grid(~ drug)

```
