---
title: "Phenotypic Profiling of Drugs"
author: "Jan Sauer"
date: "10.11.2017"
output: 
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(PROMISE)
library(ggplot2)
library(rhdf5)
library(ape)
library(cluster)
library(Rtsne)
library(caret)
library(pheatmap)
```

# Clinical Library

```{r}
features = readRDS("../../quality_control/human/QC_human__stability_selection__features.rds")
metadata = readRDS("../../quality_control/human/QC_human__stability_selection__features_metadata.rds")
layout = substr(rownames(features), 12, 14)
features = features[layout %in% c("L08"), ]
metadata = metadata[layout %in% c("L08"), ]
```

Renormalize features to make them comparable
```{r}
features = apply(features, 2, function(x) {
  (x - mean(x)) / sd(x)})
```

# Distance maps for each drug to DMSO
```{r}
cell_line = "D004T01"
cl_features = features[metadata$CELL.LINE == cell_line, ]
cl_metadata = metadata[metadata$CELL.LINE == cell_line, ]
dmso_features = cl_features[cl_metadata$DRUG == "DMSO", ]

for(drug in unique(cl_metadata$DRUG)) {
  if(drug == "DMSO") next
  drug_features = cl_features[cl_metadata$DRUG == drug, ]
  if(nrow(drug_features) < 10) next
  combined_features = rbind(dmso_features, drug_features)
  annotation = data.frame(
    "Treatment" = cl_metadata[rownames(combined_features), "DRUG"], 
    "Concentration" = as.character(ifelse(
      test = cl_metadata[rownames(combined_features), "DRUG"] == "DMSO", 
      yes = NA, no = cl_metadata[rownames(combined_features), "CONCENTRATION"])), 
    row.names = rownames(combined_features))
  annotation_colors = list(
    "Treatment" = c("Blue", "Red"), 
    "Concentration" = c("Grey", "Yellow", "Blue", "Green", "Red"))
  names(annotation_colors$Treatment) = c("DMSO", drug)
  names(annotation_colors$Concentration) = levels(annotation$Concentration)
  pheatmap(
    mat = dist(combined_features), annotation_col = annotation, 
    annotation_colors = annotation_colors, main = drug)
}
```

<!-- # KiStem library -->

<!-- First I look at the KiStem library without concentrations -->
<!-- ```{r} -->
<!-- features = readRDS("../../quality_control/human/QC_human__stability_selection__features.rds") -->
<!-- metadata = readRDS("../../quality_control/human/QC_human__stability_selection__features_metadata.rds") -->
<!-- layout = substr(rownames(features), 12, 14) -->
<!-- features = features[layout %in% c("L02", "L03"), ] -->
<!-- metadata = metadata[layout %in% c("L02", "L03"), ] -->
<!-- ``` -->

<!-- Renormalize features to make them comparable -->
<!-- ```{r} -->
<!-- features = apply(features, 2, function(x) { -->
<!--   (x - mean(x)) / sd(x)}) -->
<!-- ``` -->

<!-- Sort treatments by how similar their replicates are. This similarity is simply the mean of the standard deviation of each individual feature across replicates. I keep only treatments that have a mean standard deviation of $\langle SD \rangle \leq 1$ for each cell line. -->
<!-- ```{r} -->
<!-- drug_conc_cl_id = paste0(metadata$DRUG, "__", metadata$CELL.LINE) -->
<!-- features_sd_agg = aggregate(features, list(drug_conc_cl_id), sd) -->
<!-- rownames(features_sd_agg) = features_sd_agg$Group.1 -->
<!-- features_sd_agg$Group.1 = NULL -->
<!-- features_sd = apply(features_sd_agg, 1, mean) -->
<!-- features_sd = data.frame( -->
<!--   "SD" = features_sd,  -->
<!--   "Drug" = sapply(strsplit(names(features_sd), "__"), "[[", 1),  -->
<!--   "Cell.Line" = sapply(strsplit(names(features_sd), "__"), "[[", 2)) -->
<!-- features_sd_sorted = list() -->
<!-- for(cl in unique(features_sd$Cell.Line)) { -->
<!--   cl_features_sd = features_sd[features_sd$Cell.Line == cl, ] -->
<!--   cl_features_sd = cl_features_sd[order(cl_features_sd$SD, decreasing = FALSE), ] -->
<!--   cl_features_sd$X = seq_len(nrow(cl_features_sd)) -->
<!--   features_sd_sorted[[cl]] = cl_features_sd -->
<!-- } -->
<!-- features_sd_sorted = do.call(rbind, features_sd_sorted) -->
<!-- ggplot(data = features_sd_sorted) + geom_line(aes(x = X, y = SD, color = Cell.Line)) -->

<!-- features_sd_thresh = features_sd_sorted[features_sd_sorted$SD <= 1, ] -->
<!-- drugs_to_keep = unique( -->
<!--   c("DMSO", names(which(table(features_sd_thresh$Drug) == length(unique(metadata$CELL.LINE)))))) -->

<!-- features = features[metadata$DRUG %in% drugs_to_keep, ] -->
<!-- metadata = metadata[metadata$DRUG %in% drugs_to_keep, ] -->
<!-- ``` -->

<!-- From here, all operations are performed on individual cell lines. Calculate the difference vector pointing from DMSO to the treatment in feature space. -->
<!-- ```{r} -->
<!-- cell_line = "D004T01" -->
<!-- cl_features = features[metadata$CELL.LINE == cell_line, ] -->
<!-- cl_metadata = metadata[metadata$CELL.LINE == cell_line, ] -->

<!-- cl_features_mean = aggregate(cl_features, list(cl_metadata$DRUG), mean) -->
<!-- rownames(cl_features_mean) = cl_features_mean$Group.1 -->
<!-- cl_features_mean$Group.1 = NULL -->
<!-- for(feat in colnames(cl_features_mean)) { -->
<!--   cl_features_mean[[feat]] = cl_features_mean[[feat]] - cl_features_mean["DMSO", feat] -->
<!-- } -->
<!-- ``` -->

<!-- t-SNE -->
<!-- ```{r} -->
<!-- perplexities = c(10, 20, 30, 40, 50) -->
<!-- tsne_data = lapply(perplexities, function(x) Rtsne( -->
<!--   cl_features_mean, perplexity = x, initial_dims = 250,  -->
<!--   theta = 0, pca_scale = TRUE, pca_center = TRUE, max_iter = 5000)) -->
<!-- names(tsne_data) = perplexities -->
<!-- for(x in perplexities) { -->
<!--   tsne_df = data.frame(tsne_data[[as.character(x)]]$Y) -->
<!--   plot( -->
<!--     ggplot(data = tsne_df) + geom_point(aes(x = X1, y = X2)) +  -->
<!--       ggtitle(sprintf("T-SNE Plot with perplexity %s", x))) -->
<!-- } -->
<!-- ``` -->

<!-- K-Means clustering -->
<!-- ```{r} -->
<!-- pam1 = function(x, k) list(cluster = pam(x, k, cluster.only = TRUE)) -->
<!-- gapstat = clusGap(x = cl_features_mean, FUNcluster = pam1, K.max = 20, B = 50, verbose = FALSE) -->
<!-- plot(gapstat, main = "Gap Statistic for Full Feature Set") -->
<!-- ``` -->

<!-- Hierarchical Clustering -->
<!-- ```{r} -->
<!-- dmat = dist(as.matrix(cl_features_mean)) -->
<!-- hc = hclust(dmat) -->
<!-- colors = c("Black", "Red") -->
<!-- is_dmso = as.numeric(hc$labels == "DMSO") + 1 -->
<!-- plot.phylo( -->
<!--   as.phylo(hc), cex = 0.6, label.offset = 0.5, type = "fan",  -->
<!--   show.tip.label = FALSE, edge.color = colors[as.factor(is_dmso)],  -->
<!--   tip.color = colors[as.factor(is_dmso)]) -->
<!-- ``` -->
