Clustering of a single plate

```{r, message=FALSE, warning=FALSE, include=FALSE}
library(PROMISE)
library(ggplot2)
library(rhdf5)
library(Rtsne)
library(data.table)
library(fpc)

# Directories and files
# config_dir = "/collab-ag-fischer/PROMISE/data-10x-4t-c-16z/configdir"
config_dir = "/local-collab-ag-fischer/PROMISE/data-10x-4t-c-16z/configdir"
feature_dir = "/collab-ag-fischer/PROMISE/data-10x-4t-c-16z/features"
source(file.path(config_dir, "watchdogConfig.R"))

# Parameters
feature_type = "organoids"
```

Load Data
```{r}
cell_line = "D004T01"
feature_file = sprintf("OrganoidClustering_%s_features.rds", cell_line)
metadata_file = sprintf("OrganoidClustering_%s_metadata.rds", cell_line)
if(file.exists(feature_file)) {
  features = readRDS(feature_file)
  metadata = readRDS(metadata_file)
} else {
  # plates = list.files(feature_dir, pattern = cell_line)[2]
  plates = c("D004T01P003L02", "D004T01P007L02")
  # TODO: Add logic to remove reimaged plates
  # Sort plates by number and layout ID
  plate_ids = substr(plates, 10, 14)
  plates = plates[order(plate_ids)]
  
  all_features = vector(mode = "list", length = length(plates)*384)
  object_types = vector(mode = "list", length = length(plates)*384)
  list_counter = 1
  for(plate in plates) {
    wells = list.files(file.path(feature_dir, plate, "wells_normalized"), plate)
    for(well in wells) {
      features_fn = file.path(feature_dir, plate, "wells_normalized", well)
      features = data.frame(h5read(features_fn, sprintf("features_%s", feature_type)))
      colnames(features) = h5read(features_fn, sprintf("feature_names_%s", feature_type))
      well_id = paste0(strsplit(well, "_")[[1]][1:3], collapse = "_")
      rownames(features) = paste0(well_id, "_", seq_len(nrow(features)))
      all_features[[list_counter]] = features
      object_types[[list_counter]] = h5read(features_fn, sprintf("object_type_%s", feature_type))
      list_counter = list_counter + 1
      H5close()
    }
  }
  rnames = lapply(all_features, rownames)
  rnames = unlist(rnames)
  
  all_features = data.frame(rbindlist(all_features))
  rownames(all_features) = rnames
  object_types = do.call(c, object_types)
  
  # Set up metadata
  rep_dict = c()
  layout_id = substr(rnames, 12, 14)
  for(lid in unique(layout_id)) {
    plate_id = substr(rnames, 10, 14)[layout_id == lid]
    rep_dict = c(rep_dict, setNames(seq_along(unique(plate_id)), unique(plate_id)))
  }
  replicates = rep_dict[substr(rnames, 10, 14)]
  
  # Load the drug libraries
  layouts = list()
  for(lid in unique(layout_id)) {
    layouts[[lid]] = loadLibrary(
      library = lid, configdir = config_dir, 
      cols = c("Well_ID_384", "Product.Name", "concentration", "Target"))
    layouts[[lid]]$Layout.ID = lid
  }
  layouts = do.call(rbind, layouts)
  
  rnames_layout_ids = paste0(
    substr(rnames, 12, 14), ".", 
    substr(rnames, 16, 16), substr(rnames, 18, 19))
  drugs = as.character(layouts[rnames_layout_ids, "Product.Name"])
  target = as.character(layouts[rnames_layout_ids, "Target"])

  metadata = data.frame(
    "OBJECT.TYPE" = object_types, 
    "REPLICATE" = replicates, 
    "CELL.LINE" = substr(rnames, 1, 7), 
    "DRUG" = drugs, 
    "TARGET" = target, 
    row.names = rnames)
  
  saveRDS(object = all_features, file = feature_file)
  saveRDS(object = metadata, file = metadata_file)
  features = all_features
}
```

Perform Stability Selection to reduce dimensionality. The stability selection relies on correlation between replicates, so it is performed on the averages within a treatment for each replicate.
```{r}
stab_select_file = sprintf("OrganoidClustering_%s_stabilitySelection_results.rds", cell_line)
stab_select_features_file = sprintf("OrganoidClustering_%s_stabilitySelection_features.rds", cell_line)
if(file.exists(stab_select_file)) {
  selection = readRDS(stab_select_file)
  features_sel = readRDS(stab_select_features_file)
} else {
  source("../functions/StabilitySelection.R")
  
  # Calculate the treatment averages of each feature
  features_agg = aggregate(
    x = features, by = list(metadata$REPLICATE, metadata$CELL.LINE, metadata$DRUG), 
    FUN = median, na.rm = TRUE)
  metadata_agg = features_agg[, c("Group.1", "Group.2", "Group.3")]
  colnames(metadata_agg) = c("REPLICATE", "CELL.LINE", "TREATMENT")
  features_agg$Group.1 = NULL
  features_agg$Group.2 = NULL
  features_agg$Group.3 = NULL
  
  # Set initial features
  initial_features = c("x.0.s.area")
  
  # Remove features with NA's in them
  na_feature_vals = colSums(!is.finite(as.matrix(features_agg)))
  features_reduced = features_agg[, na_feature_vals == 0]
  
  # Remove features with not enough variety
  feature_range = apply(features_reduced, 2, function(x) mad(x, na.rm = TRUE))
  features_reduced = features_reduced[, feature_range > 0]
  
  # Remove highly correlated features (rho >= 0.95)
  # Perform on subset to decrease runtime
  features_cor = cor(features_reduced, use = "pairwise.complete.obs")
  feature_cor_vector = features_cor[upper.tri(features_cor, diag = FALSE)]
  features_cor[upper.tri(features_cor, diag = TRUE)] = 0
  features_to_keep = names(which(!apply(features_cor,2,function(x) any(abs(x) > 0.95))))
  features_reduced = features_reduced[,features_to_keep]
  
  # Ensure that the initial features for the stability selection are still in the dataset
  for(initial_feature in initial_features) {
    if(!initial_feature %in% colnames(features_reduced))
      features_reduced[[initial_feature]] = features_agg[[initial_feature]]
  }
  
  # # To save time, the stability selection will be run over a subset of the data.
  # # To this end, select a random selection of organoids for each treatment (to get the 
  # # full diversity)
  # all_treatments = as.character(unique(metadata$DRUG))
  # num_samples = ceiling(10000 / length(all_treatments))
  # selection_indices = c()
  # for(treatment in all_treatments) {
  #   # Rep 1
  #   selection_indices = c(selection_indices, sample(
  #     which(metadata$DRUG == treatment & metadata$REPLICATE == 1), 
  #     num_samples / 2, replace = FALSE))
  #   # Rep 2
  #   selection_indices = c(selection_indices, sample(
  #     which(metadata$DRUG == treatment & metadata$REPLICATE == 2), 
  #     num_samples / 2, replace = FALSE))
  # }
  # features_reduced = features_reduced[selection_indices, ]
  # metadata_reduced = metadata[selection_indices, ]
  
  # Calculate the z score of the features
  
  # Perform stability selection
  selection = selectByStability(
    features = features_reduced, metadata = metadata_agg, 
    preselect = initial_features, Rdim = 100, verbose = TRUE)
  
  # Keep only the selected features until the ratio drops to 0.5
  selected_features = na.omit(selection$selected[selection$ratioPositive >= 0.5])
  
  features_sel = features[, selected_features]
  
  saveRDS(object = selection, file = stab_select_file)
  saveRDS(object = features_sel, file = stab_select_features_file)
}
```

Prune features that don't have values for all organoids
```{r}
features_sel = features_sel[, apply(features_sel, 2, function(x) sum(!is.finite(x))) == 0]
```

Perform t-SNE for the DMSO controls
```{r}
features_dmso = features_sel[metadata$DRUG == "DMSO", ]
metadata_dmso = metadata[metadata$DRUG == "DMSO", ]

features_dmso = features_dmso[sample(seq_len(nrow(features_dmso)), 1000, replace = FALSE), ]

tsne = Rtsne(
  X = features_dmso, perplexity = 5, initial_dims = ncol(features_dmso), 
  theta = 0, pca_scale = TRUE, pca_center = TRUE)
```

```{r}
ggplot(data = as.data.frame(tsne$Y)) + geom_point(aes(x = V1, y = V2))
```


Clustering
```{r}
clustering = pamk(
  data.frame(features_sel), krange = 2:10, 
  criterion = "ch", usepam = TRUE, scaling=TRUE, ns=10)
print(sprintf("Optimal number of clusters: %s", clustering$nc))
```