---
title: "PCA EDA"
author: Niklas Rindtorff
output:
  pdf_document: default
  html_document:
    keep_md: true
params:
  data: "data/processed/PhenotypeSpectrum/filtered_moderate/pca_absolute_all_drugs_sampled.Rds"
  remote: FALSE
  cache: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = params$cache,
                      message = FALSE,
                      warning = FALSE)
```


```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(magrittr)
library(purrr)
library(readr)
library(here)
library(ggrastr)
library(cowplot)
library(princurve)
library(scico)
library(ggridges)

# parameter
print("parameter input:")
print(params$data)
```


```{r}
pca_df <- read_rds(here::here(params$data))

organoid_morphology <- read_delim(here::here("references/imaging/visual_classification_organoids.csv"), ";", escape_double = FALSE, trim_ws = TRUE) %>% 
  dplyr::select(line = organoid, morphology = visual_inspection_v2)


```

# difficulties
* inclusion of dead organoids during PCA
* inclusion of D021T01


```{r}
pca_df %>% 
  ggplot(aes(size_log)) + 
  geom_density() + 
  facet_wrap(~ line)
```



```{r}
pca_dmso <- pca_df %>% filter(drug == "DMSO") %>% 
  filter(size_log > 7.5) %>%
  group_by(line, screen_id) %>% 
  summarise_at(vars(contains("pc"), size_log), funs(mean)) %>% 
  ungroup() %>%
    left_join(organoid_morphology %>% mutate(line = paste0(line, "01"))) 
```



```{r}
pca_df %>% 
  ggplot(aes(pc1, pc2, color = size_log)) + 
  geom_point_rast()
```

```{r}
pca_dmso %>% 
  ungroup() %>%
  dplyr::select(-(line:screen_id), -morphology) %>% 
  cor() %>% 
  pheatmap::pheatmap()
```



```{r}
pca_dmso %>% 
  ggplot(aes(pc1, pc2, color = size_log, label = line)) + 
  geom_point() + 
  ggrepel::geom_text_repel() + 
  scale_color_viridis_c()
  
```


```{r}
pca_dmso %>% 
  ungroup() %>%
 dplyr::select(-(line:screen_id), -morphology) %>% 
  cor() %>% 
  pheatmap::pheatmap()
```
```{r}
pheatmap::pheatmap(
  mat = pca_dmso %>% ungroup() %>% mutate(id = paste0(line, screen_id)) %>% 
    #mutate(size_log = scale(size_log)) %>%
    dplyr::select(contains("pc"), id) %>% as.data.frame() %>% column_to_rownames("id"),
  annotation_row = pca_dmso %>% 
    mutate(id = paste0(line, screen_id)) %>% dplyr::select(line, screen_id, id, morphology) %>% as.data.frame() %>% column_to_rownames("id")
)
```


```{r, eval = FALSE}
df <- pca_dmso %>% ungroup() %>%
    left_join(organoid_morphology %>% mutate(line = paste0(line, "01"))) %>% 
  drop_na()

model = lm(morphology ~ pc3, data = df %>% mutate(morphology = factor(morphology)))

model
```

```{r}
pca_dmso
```



```{r}
pca_dmso %>% 
  ggplot(aes(pc20, size_log, color = size_log,label = line)) + 
  geom_point() + 
  ggrepel::geom_text_repel()
```

```{r}
pca_dmso %>% 
  ggplot(aes(pc1, pc2, color = morphology, label = line)) + 
  geom_point() + 
  ggrepel::geom_text_repel() + 
  #scale_color_viridis_c() + 
  theme_cowplot()
```

