---
title: "brightfield_images"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(EBImage)
library(reshape2)
```

```{r}
assay <- "incoming/PROMISE-4x-1t-1z-Brightfield-fast"
path <- '/Volumes/collab-bernd-fischer/PROMISE/'
#path <- '/Volumes/Macintosh HD/Users/rindtorf/promise/local_data/'
pattern <- 'T01P005'
filelist <- list.files(paste0(path, assay), pattern = pattern, full.names = TRUE)
dir <- paste0(path, assay, "/")
```

```{r}
#load 100 random images and calculate the mean of the matrix 
test <- list.files(filelist, pattern = ".tif", full.names = TRUE) %>% 
  as.data.frame(stringsAsFactors = FALSE) %>%
  sample_n(100) %>%
  .$. %>%
  readImage(.,all = TRUE)
  
#calculate mean of the 100 loaded images 
test.mean <- apply(simplify2array(test), 1:2, mean)
save(file = "mean_img_100.RData", test.mean)

#define Gaussian filter
w = makeBrush(size = 31, shape = 'gaussian', sigma = 100)
test.mean.blur <- filter2(test.mean, w)# %>% 
  #normalize #%>%
  
#show random image 
display(normalize(test), method = 'raster')
#show reference image 
display(normalize(test.mean.blur), method = 'raster')

#divide by average intensity to define a correction image
test.mean.scalar <- mean(test.mean)
correction.img <- test.mean.scalar/test.mean.blur


```

```{r}
#select the random image
raw.img <- test[,,1]

#crop the random image and its correction mask
raw.img.trim <- raw.img[160:1808, 160:1808]
correction.img.trim <- correction.img[160:1808, 160:1808]

#correct the random image
img.trim.cor <- raw.img.trim*correction.img.trim 

#display corrected and cropped image
img.trim.cor %>% normalize %>% display(method = 'raster')

#show the histograms of image pre- and post-processing
raw.img.trim %>%  hist(main = 'unprocessed brightfiled image')
img.trim.cor %>% as.Image %>% hist(main = 'cropped and corrected brightfield image')
```

Write a function to load a single image, crop and correct it. 
```{r}
#crop and flat-field correction
cffc <- function(img.path, ff.img){
  #isolate the identifier of the image 
  img.name <- substr(img.path,82,165)
  img.path.dir <- substr(img.path,82,131)
  dir.create(
    paste0("local_data/", img.path.dir), recursive = TRUE)
  
  #load an image
  img.raw <- readImage(img.path, all = FALSE)
  
  #give status 
  cat(paste0(img.name, " loaded"))
  
  #crop and normalize image with the ff.img reference
  img.trim <- img.raw[160:1808, 160:1808]
  ff.img.trim <- ff.img[160:1808, 160:1808]
  img.trim.ff <- img.trim*ff.img.trim
  
  
  #give status 
  cat(paste0(img.name, " processed"))
  
  #write the image file 
  EBImage::writeImage(img.trim.ff, files = paste0("local_data/", img.name, "_cffc", ".tif"))

}


```

```{r}
#build worklist of images that should be processed
img.path <- list.files(filelist, pattern = ".tif", full.names = TRUE) %>% 
  as.data.frame(stringsAsFactors = FALSE) %>%
  sample_n(500) %>%
  .$. 

#process images in batch mode
lapply(img.path, cffc, ff.img = correction.img)
```

