---
title: "clinical_cancer_panel"
author: "Niklas R"
date: "29 3 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the Selleck order list with well annotation and global library list from two excel sheets
```{r}
library(tidyverse)
library(readxl)

DrugPanel_PROMISE_Maerz17 <- read_excel("~/promise_local/DrugPanel_PROMISE_Maerz17.xlsx", 
    sheet = "Concentrations_tidy")
```


Develop the plate layout for the library using a tool by Bernd Fischer
```{r}
source('~/promise_local/scripts/samplePlateDesign_fixNR.R')
```

```{r}
temp <- plates %>%
  select(substance)%>%
  unique() %>%
  arrange(substance)

temp <- cbind(DrugPanel_PROMISE_Maerz17, temp$substance)
colnames(temp)[28] <- "substance"
temp <- merge(plates, temp, by = "substance")

robot <- temp %>% 
  select(`Drug Name`,
          substance,
         concentration,
         rack_position,
         well) 
  
```


#Create the Clinical Cancer Panel matching the procedure of the KiStem library
Load pipetting layout from KiStem library
```{r}
library(readr)
KiStem_edt_V170125 <- read_csv("~/C/compound_libraries/KiStem_edt_V170125.csv")

```

```{r}
temp <- KiStem_edt_V170125[1:384,]
temp[,2:ncol(temp)] <- NA 

temp$`Product Name` = robot$`Drug Name`
temp$Well_ID_384 = robot$well
temp$Plate_ID_384 = "L08"
temp$concentration_factor = robot$concentration

CCPanel <- temp %>%
  mutate(concentration_factor = as.numeric(concentration_factor)) %>%
  mutate(concentration_factor = replace(
    concentration_factor, which(concentration_factor == 1), 0.2)) %>%
  mutate(concentration_factor = replace(
    concentration_factor,  which(concentration_factor == 2), 0.2)) %>%
  mutate(concentration_factor = replace(
    concentration_factor,  which(concentration_factor == 3), 0.04)) %>%
  mutate(concentration_factor = replace(
    concentration_factor,  which(concentration_factor == 4), 0.008)) %>%
  mutate(concentration_factor = replace(
    concentration_factor,  which(concentration_factor == 5), 0.0016))
  

```

```{r}
library(xlsx)

write.csv(CCPanel, "Clin_Cancer_Panel_V170511.csv")

write.xlsx(as.data.frame(CCPanel), file = "Clin_Cancer_Panel_V170511.xlsx",
        sheetName = "Library", row.names = FALSE)
```

