---
title: "analyse_CTG_PROMISE"
author: "NR"
date: "16 May 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
library(tidyverse)
library(HTSvis)
library(readr)
```

##Load data into session
```{r}
assay <- "qgel/"
pattern <- 'L98.TXT'
filelist <- list.files(paste0('/Volumes/collab-bernd-fischer/PROMISE/ctg_data/', assay), pattern = pattern)
dir <- paste0("/Volumes/collab-bernd-fischer/PROMISE/ctg_data/", assay)


load_delim <- function(path, name){
  read_delim(paste0(path, name), 
    "\t", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)
}

tmp_list <- lapply(filelist, load_delim, path = dir)
tmp <- do.call('rbind', tmp_list)


Clin_Cancer_Panel_V170511 <- read_csv("/Volumes/collab-bernd-fischer/PROMISE/layouts/raw_layout_files/Clin_Cancer_Panel_V170511.csv")

```
```{r}
colnames(tmp) <- c('barcode', 'Well_ID_384', 'photons')

tmp <- tmp %>% 
  mutate(barcode_2 = barcode,
         run = paste0(substr(barcode, 14, 20), substr(barcode, 25, 27)),
         number = 1)
```


##Load CTG data and combine with library annotation L08

```{r}
l08 <- Clin_Cancer_Panel_V170511 %>%
  select(`Product Name`, Well_ID_384, concentration_factor)

merged  <- merge(tmp, l08, by = 'Well_ID_384') 

  
```

##Save data to DEsktop for HTSViz analysis
```{r}
write.csv(merged, "/Users/b110/Desktop/D007TL08.csv")
```

```{r}
HTSvis()
```