---
title: "manual_classification"
author: "Niklas Rindtorff"
date: "3/27/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

Load packages

```{r}
library(tidyverse)
library(readxl)
```

Load data

```{r}
manual_classification <- read_excel("~/promise/local_data/observation/PDO_manual_classification.xlsx")
```

Plot data

```{r}
manual_classification %>% 
  mutate(Line = ifelse(Line %in% c(4, 7), paste0("0",Line), Line)) %>%
  mutate(Line = as.character(Line) %>% paste0("D0", Line) %>% substr(., 3, 7)) %>%
  mutate(Unsupervised = paste0("Group ", as.character(Unsupervised))) %>%
  ggplot(aes(Cystic, Size, color = Unsupervised)) + 
  geom_point(size = 4) + 
  ggrepel::geom_text_repel(aes(label = Line), color = "black", point.padding = 0.3) +
  theme_classic(base_size = 12) +
  #scale_color_manual(values = c('#b2182b','#ef8a62','#fddbc7','#d1e5f0','#67a9cf','#2166ac')) + 
  scale_color_manual(values = c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c')) +
  #stat_ellipse() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
        #axis.line = element_line(arrow = arrow())) 

  
```

#Alternative approach 

```{r}
load("~/promise/local_data/observation/Phenoprints_human.rda")
```

```{r}
manual_classification %>% 
  mutate(Line = ifelse(Line %in% c(4, 7), paste0("0",Line), Line)) %>%
  mutate(Line = as.character(Line) %>% paste0("D0", Line, "T01") %>% substr(., 3, 9)) %>%
  mutate(Unsupervised = paste0("Group ", as.character(Unsupervised))) %>% mutate(Cystic_group = ifelse(Cystic < 5, "disorganized", ifelse(Cystic < 9, "intermediate", ifelse(Cystic <16, "organized", NA)))) %>% left_join(., phenoprints %>% filter(Feature %in% c("Area"))) %>%
  ggplot(aes(Cystic_group, Value, color = Unsupervised)) + 
  geom_jitter(size = 4, width = 0.003) + 
  ggrepel::geom_text_repel(aes(label = Line), color = "black", point.padding = 0.3) +
  theme_classic(base_size = 12) +
  #scale_color_manual(values = c('#b2182b','#ef8a62','#fddbc7','#d1e5f0','#67a9cf','#2166ac')) + 
  scale_color_manual(values = c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c')) +
  #stat_ellipse() +
  ylab('size') + 
  xlab("cystic phenotype group") + 
  theme(#axis.text.x=element_blank(),
    axis.text.x = element_text(color = "black", size = 11),
        axis.text.y = element_text(color = "black", size = 11),
        #axis.ticks.x=element_blank(),
        #axis.text.y=element_blank(),
        #axis.ticks.y=element_blank(),
        legend.position="none")
  
```

