---
title: "z-stack"
author: "NR"
date: "3/10/2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load packages 
```{r}
library(EBImage)
library(rhdf5)
library(dplyr)
library(tidyr)
library(readr)
library(parallel)
```


#Display UMAP data
```{r}
mco_colors <- c("#cccccc", "#ffb54d" ,"#52bde0", "#629d85")

df_ft <- readRDS("~/mco/LineDifferences/FeatureAnalysis/line_differences/umap_dmso.Rdata")
df_ft_ss <- df_ft %>% 
  mutate(Line = factor(Line, levels = c("M001W01", "M001K02", "M001A03", "M001B04"))) %>%
  filter(abs(V1) < 15, abs(V2) < 7.5) 

df_ft_ss %>% 
  ggplot(aes(V1, V2, color = Line)) + 
  geom_point(size = 0.1) + 
  theme_classic() + 
  scale_color_manual(values=mco_colors) +
  geom_hline(yintercept = -3) +
  geom_vline(xintercept = 7.5) +
  facet_grid(Replicate ~ Line)
```

##subset umap data 

```{r}
set.seed(42)
#ab cluster
df_ft_ab <- df_ft_ss %>% 
  mutate(Line = factor(Line, levels = c("M001W01", "M001K02", "M001A03", "M001B04"))) %>%
  filter(V1 > 7.5, V2 < -3)

df_ft_ab_w <- df_ft_ss %>% 
  mutate(Line = factor(Line, levels = c("M001W01", "M001K02", "M001A03", "M001B04"))) %>%
  filter(Line == "M001B04") %>%
  filter(V1 > 0, V2 > 4)

compounds <- df_ft_ab %>% dplyr::select(2:11) %>% 
  sample_frac(.,size = 0.001) %>% 
  mutate(well = paste0(substr(Well, 1,1), "_",substr(Well, 2,3)),
         name = paste0(substr(Plate, 12,14), "_", well, '_contrastProjections.h5'),
         plate_barcode = Plate) #L08_G_14_contrastProjections.h5

compounds <- df_ft_ab_w %>% dplyr::select(2:11) %>% 
  sample_frac(.,size = 0.01) %>% 
  mutate(well = paste0(substr(Well, 1,1), "_",substr(Well, 2,3)),
         name = paste0(substr(Plate, 12,14), "_", well, '_contrastProjections.h5'),
         plate_barcode = Plate) #L08_G_14_contrastProjections.h5

#write.csv(compounds, file = "df_ft_ab_w.csv")
```


#Load annotation and define compounds of interest
Drugs targeting MEK are selected from all tested libraries
```{r, eval = FALSE}
kistem_lib <- read_csv("~/mco/local_data/compound_libraries/KiStem_edt_V170125.csv") %>%
  dplyr::select(contains("Product"), Target, Row_ID_384, Col_ID_384, Plate_ID_384) %>% #build a compound repository
  filter(grepl(Target, pattern = 'MEK')) %>%
  select(-Target) %>%
  mutate(Plate_ID_384 = if_else(Plate_ID_384 == "01", "L01", "L02"))


ccp_lib <- read_delim("~/promise/local_data/layouts/Clin_Cancer_Panel_V170511.csv", 
                      ";", escape_double = FALSE, trim_ws = TRUE) 
colnames(ccp_lib)[c(1, 3, 6)] <- c("Product Name", "concentration_factor", "Well_ID_384")

compounds <- ccp_lib %>%  
  select(`Product Name`, Well_ID_384, concentration_factor) %>%
  dplyr::filter(!grepl(`Product Name`, pattern = 'mit')) %>%
  dplyr::filter(`Product Name` == "DMSO") %>%
  mutate(`Product Name` = paste0(`Product Name`, "_", concentration_factor),
         Plate_ID_384 = "L08") %>%
  separate(Well_ID_384, c("Row_ID_384", "Col_ID_384"), sep = 1) %>%
  select(-concentration_factor) %>%
  #rbind(.,kistem_lib) %>%
  rename(anno = `Product Name`) %>%
  mutate(well = paste0(Row_ID_384, "_", Col_ID_384),
       name = paste0(Plate_ID_384, "_", well, '_contrastProjections.h5'))

# compounds <- compounds %>%
#   filter(well %in% c("B_24", "E_19", "P_23")) 

compounds <- compounds %>%
  sample_frac(.,size = 0.1)

compounds
```

#Define filenames and applicable organoid lines 
```{r}
destination = "~/Desktop/"
dir = "/Volumes/share/rauscher/promise/PROMISE/data-10x-4t-c-16z/hdf5projection/"

organoids <- list.files(dir, pattern = "M0") %>%
  substr(., 1, 14) %>%
  unique() %>%
  as_tibble() %>%
  rename(plate_barcode = value) %>%
  #filter(grepl(plate_barcode, pattern = 'L08')) %>%
  mutate(path = paste0(dir, plate_barcode, "/", substr(plate_barcode, 1, 11)))

##use list files for this
# load(file = paste0("/Volumes/Macintosh HD/Users/rindtorf/promise/local_data/ctg_ccp_unfiltered.Rdata"))
# organoids <- tmp %>% 
#   select(plate_barcode) %>% 
#   unique() %>%
#   mutate(path = paste0(dir, plate_barcode, "/", substr(plate_barcode, 1, 11)))

organoids
```


#Define file names
```{r}
# treatments <- expand.grid(name = compounds$name, plate_barcode = organoids$plate_barcode) %>%
#   left_join(organoids) %>%
#   left_join(compounds) %>%
#   unite(full_path, path, name, sep = "")

treatments <- left_join(compounds, organoids) %>% unite(full_path, path, name, sep = "") %>%
  mutate(anno = paste0(Drug, "_", Line))
  
  
    
store_image <- function(string, df){
#define further variables 
anno <- df %>% 
    filter(full_path == string) %>%
    select(anno, plate_barcode)
  
#Load images
H5 = h5read(string, "images")

#Write raw images to file
test <- Image(data = normalize(log(H5[,,c(1,2,3),c(1,2,4,3)])), colormode = "Color")
writeImage(test, paste0(destination,"rgb_", anno$anno, "_", anno$plate_barcode, ".png"))
cat("writing image /n")
}

lapply(treatments$full_path, store_image, df = treatments)

```
